apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "ml-api.fullname" . }}
  labels:
    {{- include "ml-api.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "ml-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "ml-api.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "ml-api.serviceAccountName" . }}

      containers:
        - name: ml-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- if .Values.secret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.existingSecret }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
